Update index.tsx
Kieran-McIntyre/react-native-section-alphabet-list pull request #27
Opened 2021-11-23 17:13 UTC by aytajj

2021-11-23 18:34 UTC, Kieran-McIntyre requested changes
Hi @aytajj!

Thanks for this. This change looks good, but since we're using TypeScript here, we need to update the interface [here](https://github.com/Kieran-McIntyre/react-native-section-alphabet-list/blob/master/src/components/ListLetterIndex/types.ts) with the new prop. That's why we're seeing the unit tests fail.

I would give updating this a go, and I would also add a unit test to the component to test that the custom style is applied to the `FlatList` element. Please let me know if you would like any help/guidance.

Thanks!

2021-11-23 19:15 UTC, aytajj commented
@Kieran-McIntyre, thank you for reply, I changed pull request. Can you please check?

2021-11-23 19:21 UTC, Kieran-McIntyre commented
> Details

Hi @aytajj. Thanks for making that change. The unit tests are still failing. Can you please fix them? Once they are updated, I will take another look. Thanks!

2021-11-23 20:04 UTC, aytajj commented
Dear @Kieran-McIntyre, I think it will work now. Can you please check?

2021-11-23 21:59 UTC, Kieran-McIntyre commented
> Dear @Kieran-McIntyre, I think it will work now. Can you please check?

Hi @aytajj. The tests are still failing. Can you please run the tests locally before pushing your commit to ensure they're passing? Run command `yarn test` in your terminal.

2021-11-24 05:49 UTC, aytajj commented
Hi @Kieran-McIntyre, I am sorry,  letterListContainerStyle must be optional.  I added question mark. Test was successful. Thank you

2021-11-24 18:19 UTC, aytajj commented
@Kieran-McIntyre can you please check? All tests was successful.

2021-11-24 23:58 UTC, Kieran-McIntyre commented
> @Kieran-McIntyre can you please check? All tests was successful.

Thanks @aytajj. One last thing, please could you update the `README.md` with the new prop?

2021-11-25 00:03 UTC, Kieran-McIntyre reviewed
Looks good, just final minor comments 👍

2021-11-25 00:03 UTC, Kieran-McIntyre commented on src/components/AlphabetList/types.ts
> +  letterListContainerStyle?: CSSProperties,
This should also be `ViewStyle` here

```suggestion
  letterListContainerStyle?: ViewStyle,
```

2021-11-25 00:03 UTC, Kieran-McIntyre commented on src/components/ListLetterIndex/index.test.tsx
> +    it('letterListContainerStyle > should apply custom style', () => {
```suggestion

    it('letterListContainerStyle > should apply custom style', () => {
```

2021-11-25 00:03 UTC, Kieran-McIntyre commented on src/components/ListLetterIndex/index.test.tsx
> +        // Assert.
```suggestion
      
          // Assert.
```

2021-11-25 00:03 UTC, Kieran-McIntyre commented on src/components/AlphabetList/types.ts
> +import { SectionListData, SectionListProps, TextStyle, ViewStyle, CSSProperties } from "react-native";
```suggestion
import { SectionListData, SectionListProps, TextStyle, ViewStyle } from "react-native";
```

2021-11-25 07:07 UTC, aytajj commented
Hi @Kieran-McIntyre, I've updated the pull request, please check it out. Thanks.

2021-11-25 18:15 UTC, aytajj commented
Hi, @Kieran-McIntyre, Would you please check?

2021-11-25 19:45 UTC, Kieran-McIntyre approved these changes

2021-11-25 19:49 UTC, merged

2021-11-25 20:00 UTC, Kieran-McIntyre commented
> Hi, @Kieran-McIntyre, Would you please check?

@aytajj  this has now been merged and published. Your change can be found in `v2.1.0`. Thanks!

2021-11-26 06:06 UTC, aytajj commented
@Kieran-McIntyre , Thank you!